routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| AUTH
|--------------------------------------------------------------------------
*/
// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
//Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//Route::post('password/reset', 'Auth\ResetPasswordController@reset');

//Route::get('/home', 'HomeController@index')->name('home');

/*
|--------------------------------------------------------------------------
| FRONT
|--------------------------------------------------------------------------
*/
/* Main page */
Route::get('/', 'Front\MainPageController@index')->name('main_page');

/* Number */
Route::get('/number/{slug}', 'Front\NumberController@show')->name('number.show');

/* Static pages */
Route::get('/about', 'Front\StaticPageController@about')->name('static_page.about');
Route::get('/contacts', 'Front\StaticPageController@contacts')->name('static_page.contacts');

/* Gallery */
Route::get('/gallery', 'Front\GalleryController@show')->name('gallery.show');

/* Feedback */
Route::post('/feedback-store', 'Front\FeedbackController@store')->name('feedback.store');

/* Order */
Route::post('/reserve', 'Front\OrderController@reserve')->name('order.reserve');
/*
|--------------------------------------------------------------------------
| ADMIN
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    /* Orders */
    Route::get('/', 'Admin\OrderController@index')->name('admin.orders.index');
    Route::resource('orders','Admin\OrderController')->except(['index']);

    /* Numbers */
    Route::resource('numbers','Admin\NumberController');
    Route::post('/number-save-image', 'Admin\NumberController@saveImage')->name('admin.number_save_image');
    Route::post('/number-sort-images', 'Admin\NumberController@sortImages')->name('admin.number_sort_images');
    Route::post('/number-remove-image', 'Admin\NumberController@removeImage')->name('admin.number_image_remove_image');
    Route::post('/number-image-switch-active', 'Admin\NumberController@imageSwitchActive')->name('admin.number_image_switch_active');
    Route::post('/number-add-price', 'Admin\NumberController@addPrice')->name('admin.number_add_price');
    Route::post('/number-remove-price', 'Admin\NumberController@removePrice')->name('admin.number_add_price');
    Route::post('/number-switch-active', 'Admin\NumberController@switchActive')->name('admin.number_switch_active');
    Route::post('/numbers-sort', 'Admin\NumberController@sortNumbers')->name('admin.numbers_sort');

    /* Slider */
    Route::get('/sliders', 'Admin\SliderController@index')->name('admin.sliders');
    Route::post('/slider-save-image', 'Admin\SliderController@saveImage')->name('admin.slider_save_image');
    Route::post('/slider-sort-images', 'Admin\SliderController@sortImages')->name('admin.slider_sort_images');
    Route::post('/slider-remove-image', 'Admin\SliderController@removeImage')->name('admin.slider_remove_image');
    Route::post('/slider-switch-active', 'Admin\SliderController@switchActive')->name('admin.slider_switch_active');

    /* Static pages */
    Route::get('/static-pages/{slug}', 'Admin\StaticPageController@edit')->name('admin.static_pages_edit');
    Route::put('/static-pages/{slug}', 'Admin\StaticPageController@update')->name('admin.static_pages_update');

    /* Gallery */
    Route::get('/gallery', 'Admin\GalleryController@index')->name('admin.gallery.show');
    Route::post('/gallery-save-image', 'Admin\GalleryController@saveImage')->name('admin.gallery_save_image');
    Route::post('/gallery-sort-images', 'Admin\GalleryController@sortImages')->name('admin.gallery_sort_images');
    Route::post('/gallery-remove-image', 'Admin\GalleryController@removeImage')->name('admin.gallery_remove_image');
    Route::post('/gallery-image-switch-active', 'Admin\GalleryController@switchActive')->name('admin.gallery_switch_active');
    Route::post('/gallery-enable-numbers-photo', 'Admin\GalleryController@enableNumbersPhoto')->name('admin.gallery_enable_numbers_photo');

    /* Info */
    Route::resource('info', 'Admin\InfoController');

    /* Text */
    Route::resource('texts', 'Admin\TextController');

    /* Feedback */
    Route::get('/feedback', 'Admin\FeedbackController@index')->name('admin.feedback.show');
});

app/Models/Text.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Text extends Model
{
    protected $table = 'texts';

    protected $fillable = [
        'title', 'key', 'value'
    ];
}

app/Http/Controllers/Admin/TextController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Text;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\TextStoreRequest;
use App\Http\Requests\Admin\TextUpdateRequest;

class TextController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $texts = Text::all();

        return view('admin.text.index', compact('texts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.text.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TextStoreRequest $request)
    {
        $info = Text::create($request->all());

        return redirect()->route('texts.edit', ['id' => $info->id])->with('success', 'Текст успешно создан!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $text = Text::find($id);

        return view('admin.text.edit', compact('text'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TextUpdateRequest $request, $id)
    {
        Text::find($id)->update($request->all());

        return redirect()->back()->with('success', 'Данные успешно обновлены!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Text::find($id)->delete();

        return redirect()->route('texts.index')->with('success', 'Данные успешно удалены!');

    }
}

resources/views/admin/text/create.blade.php
@extends('layouts.admin.app')

@section('content')
    <br>
    <h3 class="text-center">Создание текста</h3>
    <br>

    <div class="container">

        @include('admin.widgets.success_message')

        <form action="{{ route('texts.store') }}" method="POST">
            @csrf
            @method('POST')
            <div class="form-group">
                <label for="text-title">Название</label>
                <input type="text"
                       class="form-control {{ $errors->has('title') ? ' is-invalid' : '' }}"
                       id="text-title"
                       name="title"
                       required>

                @if ($errors->has('title'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('title') }}</strong>
                    </span>
                @endif
            </div>

            <div class="form-group">
                <label for="text-key">Ключ</label>
                <input type="text"
                       class="form-control {{ $errors->has('key') ? ' is-invalid' : '' }}"
                       id="text-key"
                       name="key"
                       required>

                @if ($errors->has('key'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('key') }}</strong>
                    </span>
                @endif
            </div>

            <div class="form-group">
                <label for="text-value">Значение</label>

                <textarea class="form-control{{ $errors->has('value') ? ' is-invalid' : '' }}"
                          name="value"
                          id="text-value"
                          rows="6"
                          placeholder="Значение"
                          required></textarea>

                @if ($errors->has('value'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('value') }}</strong>
                    </span>
                @endif
            </div>

            <br>

            <button type="submit" class="btn btn-outline-primary">Сохранить</button>

        </form>
    </div>
@endsection

resources/views/admin/text/edit.blade.php
@extends('layouts.admin.app')

@section('content')
    <br>
    <h3 class="text-center">Обновление текста</h3>
    <br>

    <div class="container">

        @include('admin.widgets.success_message')

        <form action="{{ route('texts.update', ['id' => $text->id]) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="text-title">Название</label>
                <input type="text"
                       class="form-control {{ $errors->has('title') ? ' is-invalid' : '' }}"
                       id="text-title"
                       name="title"
                       value="{{ old('title') ?? $text->title }}"
                       required>

                @if ($errors->has('title'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('title') }}</strong>
                    </span>
                @endif
            </div>

            <div class="form-group">
                <label for="text-key">Ключ</label>
                <input type="text"
                       class="form-control {{ $errors->has('key') ? ' is-invalid' : '' }}"
                       id="text-key"
                       name="key"
                       value="{{ old('key') ?? $text->key }}"
                       required>

                @if ($errors->has('key'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('key') }}</strong>
                    </span>
                @endif
            </div>

            <div class="form-group">
                <label for="text-value">Значение</label>

                <textarea class="form-control{{ $errors->has('value') ? ' is-invalid' : '' }}"
                          name="value"
                          id="text-value"
                          rows="6"
                          placeholder="Значение"
                          required>{{ old('value') ?? $text->value }}</textarea>

                @if ($errors->has('value'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('value') }}</strong>
                    </span>
                @endif
            </div>

            <br>

            <button type="submit" class="btn btn-outline-primary">Сохранить</button>

        </form>
    </div>
@endsection

resources/views/admin/text/index.blade.php
@extends('layouts.admin.app')

@section('content')
    <br>
    <h3 class="text-center">Тексты</h3>
    <br>

    <div class="container">

        @include('admin.widgets.success_message')

        <a href="{{ route('texts.create') }}" class="btn btn-outline-primary">Создать</a>

        <br>
        <br>

        <table class="table table-hover">
            <thead>
            <tr class="text-center">
                <th scope="col">Название</th>
                <th scope="col">Ключ</th>
                <th scope="col">Значение</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            @foreach($texts as $text)
                <tr class="text-center">
                    <td>{{ $text->title }}</td>
                    <td>{{ $text->key }}</td>
                    <td>{!! $text->value !!}</td>
                    <td class="text-primary">
                        <a href="{{ route('texts.edit', ['id' => $text->id]) }}">
                            <i class="fas fa-edit fa-lg"></i>
                        </a>
                    </td>
                    <td class="text-danger">
                        <form action="{{ route('texts.destroy', [$text->id]) }}" method="POST" class="text-remove-form">
                            @csrf
                            @method('DELETE')
                            <i class="far fa-trash-alt fa-lg text-remove"></i>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection