routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| AUTH
|--------------------------------------------------------------------------
*/
// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
//Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//Route::post('password/reset', 'Auth\ResetPasswordController@reset');

//Route::get('/home', 'HomeController@index')->name('home');

/*
|--------------------------------------------------------------------------
| FRONT
|--------------------------------------------------------------------------
*/
/* Main page */
Route::get('/', 'Front\MainPageController@index')->name('main_page');

/* Number */
Route::get('/number/{slug}', 'Front\NumberController@show')->name('number.show');

/* Static pages */
Route::get('/about', 'Front\StaticPageController@about')->name('static_page.about');
Route::get('/contacts', 'Front\StaticPageController@contacts')->name('static_page.contacts');

/* Gallery */
Route::get('/gallery', 'Front\GalleryController@show')->name('gallery.show');

/* Feedback */
Route::post('/feedback-store', 'Front\FeedbackController@store')->name('feedback.store');

/* Order */
Route::post('/reserve', 'Front\OrderController@reserve')->name('order.reserve');
/*
|--------------------------------------------------------------------------
| ADMIN
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    /* Orders */
    Route::get('/', 'Admin\OrderController@index')->name('admin.orders.index');
    Route::resource('orders','Admin\OrderController')->except(['index']);

    /* Numbers */
    Route::resource('numbers','Admin\NumberController');
    Route::post('/number-save-image', 'Admin\NumberController@saveImage')->name('admin.number_save_image');
    Route::post('/number-sort-images', 'Admin\NumberController@sortImages')->name('admin.number_sort_images');
    Route::post('/number-remove-image', 'Admin\NumberController@removeImage')->name('admin.number_image_remove_image');
    Route::post('/number-image-switch-active', 'Admin\NumberController@imageSwitchActive')->name('admin.number_image_switch_active');
    Route::post('/number-add-price', 'Admin\NumberController@addPrice')->name('admin.number_add_price');
    Route::post('/number-remove-price', 'Admin\NumberController@removePrice')->name('admin.number_add_price');
    Route::post('/number-switch-active', 'Admin\NumberController@switchActive')->name('admin.number_switch_active');
    Route::post('/numbers-sort', 'Admin\NumberController@sortNumbers')->name('admin.numbers_sort');

    /* Slider */
    Route::get('/sliders', 'Admin\SliderController@index')->name('admin.sliders');
    Route::post('/slider-save-image', 'Admin\SliderController@saveImage')->name('admin.slider_save_image');
    Route::post('/slider-sort-images', 'Admin\SliderController@sortImages')->name('admin.slider_sort_images');
    Route::post('/slider-remove-image', 'Admin\SliderController@removeImage')->name('admin.slider_remove_image');
    Route::post('/slider-switch-active', 'Admin\SliderController@switchActive')->name('admin.slider_switch_active');

    /* Static pages */
    Route::get('/static-pages/{slug}', 'Admin\StaticPageController@edit')->name('admin.static_pages_edit');
    Route::put('/static-pages/{slug}', 'Admin\StaticPageController@update')->name('admin.static_pages_update');

    /* Gallery */
    Route::get('/gallery', 'Admin\GalleryController@index')->name('admin.gallery.show');
    Route::post('/gallery-save-image', 'Admin\GalleryController@saveImage')->name('admin.gallery_save_image');
    Route::post('/gallery-sort-images', 'Admin\GalleryController@sortImages')->name('admin.gallery_sort_images');
    Route::post('/gallery-remove-image', 'Admin\GalleryController@removeImage')->name('admin.gallery_remove_image');
    Route::post('/gallery-image-switch-active', 'Admin\GalleryController@switchActive')->name('admin.gallery_switch_active');
    Route::post('/gallery-enable-numbers-photo', 'Admin\GalleryController@enableNumbersPhoto')->name('admin.gallery_enable_numbers_photo');

    /* Info */
    Route::resource('info', 'Admin\InfoController');

    /* Text */
    Route::resource('texts', 'Admin\TextController');

    /* Feedback */
    Route::get('/feedback', 'Admin\FeedbackController@index')->name('admin.feedback.show');
});

resources/views/layouts/admin/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/jquery-3.4.0.min.js') }}" defer></script>
    <script src="{{ asset('js/app.js') }}" defer></script>

    <script src="{{ asset('js/cropper.min.js') }}" defer></script>
    <script src="{{ asset('js/jquery-ui.js') }}" defer></script>
    <script src="{{ asset('js/datepicker.js') }}" defer></script>
{{--    <script src="{{ asset('js/ckeditor.js') }}" defer></script>--}}
    <script src="https://cdn.ckeditor.com/4.12.1/full/ckeditor.js" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <!-- Styles -->
    <link href="{{ asset('css/app.css?v=1.2') }}" rel="stylesheet">
    <link href="{{ asset('css/custom/main.css?v=1.6') }}" rel="stylesheet">
    <link href="{{ asset('css/custom/admin.css?v=2.0') }}" rel="stylesheet">

    <link href="{{ asset('css/cropper.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/jquery-ui.css') }}" rel="stylesheet">
    <link href="{{ asset('css/datepicker.css?v=1') }}" rel="stylesheet">


{{--    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/r-2.2.2/datatables.min.css"/>--}}
{{--    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/r-2.2.2/datatables.min.js" defer></script>--}}


</head>

<body>
    <div id="app">

        <!-- Navigation -->
        @include('layouts.admin.navbar')
        @include('layouts.admin.navbar_menu')

        <!-- Content -->
        <main class="content">
            @yield('content')
        </main>

    </div>

    <script src="{{ asset('js/custom/main.js?v=1.1') }}" defer></script>
    <script src="{{ asset('js/custom/admin.js?v=1.8') }}" defer></script>

</body>

</html>

resources/views/layouts/admin/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light admin-navbar">
    <div class="container">
        <a class="navbar-brand" href="{{ route('admin.orders.index') }}">
            Администратор
        </a>
        <ul class="navbar-nav ml-auto admin-navbar-right-side">
            <li class="nav-item dropdown">
                <a id="admin-navbar-dropdown" class="nav-link dropdown-toggle text-violet" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    <i class="fas fa-user"></i> <span class="caret"></span>
                </a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="admin-navbar-dropdown">
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        Выход
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
        </ul>
    </div>
</nav>

resources/views/layouts/admin/navbar_menu.blade.php
<nav class="navbar navbar-expand-md navbar-light admin-navbar-menu">
    <div class="container">

        <h5 class="admin-navbar-menu-text">Меню</h5>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#admin-navbar-menu-collapse" aria-controls="admin-navbar-menu-collapse" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse " id="admin-navbar-menu-collapse">
            <ul class="nav navbar-nav mx-auto nav-fill w-100 ">

                <li class="nav-item">
                    <a class="nav-link {{ (Request::is('admin/numbers') || (Request::is('admin/numbers/*'))) ? 'admin-nav-link-active' : '' }}" href="{{ route('numbers.index') }}">
                        <span class="nav-link-text">Номера</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link {{ Request::is('admin/gallery') ? 'admin-nav-link-active' : '' }}" href="{{ route('admin.gallery.show') }}">
                        <span class="nav-link-text">Галерея</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link {{ Request::is('admin/sliders') ? 'admin-nav-link-active' : '' }}" href="{{ route('admin.sliders') }}">
                        <span class="nav-link-text">Слайдер</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link {{ Request::is('admin/feedback') ? 'admin-nav-link-active' : '' }}" href="{{ route('admin.feedback.show') }}">
                        <span class="nav-link-text">
                            Обратная связь {{ (feedback_count() > 0) ? '(' . feedback_count() . ')' : '' }}
                        </span>
                    </a>
                </li>

                <li class="nav-item dropdown navigation-dropdown">
                    <a id="front-navbar-dropdown" class="nav-link dropdown-toggle px-3 nav-menu-link-dropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        <span class="nav-dropdown-title">
                            <span class="caret">
                                <span class="{{ Request::is('admin/static-pages/*') ? 'admin-nav-link-active' : '' }}">
                                    Страницы
                                </span>
                            </span>
                        </span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="front-navbar-dropdown">
                        @foreach($adminStaticPages as $page)
                            <a href="{{ route('admin.static_pages_edit', [$page->slug]) }}" class="nav-link px-3 admin-menu-dropdown-link">
                                <span class="{{ (request()->path() == 'admin/static-pages/' . $page->slug) ? 'admin-nav-link-active' : '' }}">
                                    {{ $page->title }}
                                </span>
                            </a>
                        @endforeach
                    </div>
                </li>
                <li class="nav-item dropdown navigation-dropdown">
                    <a id="front-navbar-dropdown" class="nav-link dropdown-toggle px-3 nav-menu-link-dropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        <span class="nav-dropdown-title">
                            <span class="caret">
                                <span class="{{ (Request::is('admin/info') || Request::is('admin/info/*')) || Request::is('admin/texts') || Request::is('admin/texts/*') ? 'admin-nav-link-active' : '' }}">
                                     Инфо
                                </span>
                            </span>
                        </span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="front-navbar-dropdown">
                        <a href="{{ route('info.index') }}" class="nav-link px-3 admin-menu-dropdown-link {{ Request::is('admin/info') || Request::is('admin/info/*') ? 'admin-nav-link-active' : '' }}">
                            Общая информация
                        </a>
                        <a href="{{ route('texts.index') }}" class="nav-link px-3 admin-menu-dropdown-link {{ Request::is('admin/texts') || Request::is('admin/texts/*') ? 'admin-nav-link-active' : '' }}">
                            Тексты
                        </a>
                    </div>
                </li>

            </ul>

        </div>

    </div>
</nav>