routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| AUTH
|--------------------------------------------------------------------------
*/
// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
//Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//Route::post('password/reset', 'Auth\ResetPasswordController@reset');

//Route::get('/home', 'HomeController@index')->name('home');

/*
|--------------------------------------------------------------------------
| FRONT
|--------------------------------------------------------------------------
*/
/* Main page */
Route::get('/', 'Front\MainPageController@index')->name('main_page');

/* Number */
Route::get('/number/{slug}', 'Front\NumberController@show')->name('number.show');

/* Static pages */
Route::get('/about', 'Front\StaticPageController@about')->name('static_page.about');
Route::get('/contacts', 'Front\StaticPageController@contacts')->name('static_page.contacts');

/* Gallery */
Route::get('/gallery', 'Front\GalleryController@show')->name('gallery.show');

/* Feedback */
Route::post('/feedback-store', 'Front\FeedbackController@store')->name('feedback.store');

/* Order */
Route::post('/reserve', 'Front\OrderController@reserve')->name('order.reserve');
/*
|--------------------------------------------------------------------------
| ADMIN
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    /* Orders */
    Route::get('/', 'Admin\OrderController@index')->name('admin.orders.index');
    Route::resource('orders','Admin\OrderController')->except(['index']);

    /* Numbers */
    Route::resource('numbers','Admin\NumberController');
    Route::post('/number-save-image', 'Admin\NumberController@saveImage')->name('admin.number_save_image');
    Route::post('/number-sort-images', 'Admin\NumberController@sortImages')->name('admin.number_sort_images');
    Route::post('/number-remove-image', 'Admin\NumberController@removeImage')->name('admin.number_image_remove_image');
    Route::post('/number-image-switch-active', 'Admin\NumberController@imageSwitchActive')->name('admin.number_image_switch_active');
    Route::post('/number-add-price', 'Admin\NumberController@addPrice')->name('admin.number_add_price');
    Route::post('/number-remove-price', 'Admin\NumberController@removePrice')->name('admin.number_add_price');
    Route::post('/number-switch-active', 'Admin\NumberController@switchActive')->name('admin.number_switch_active');
    Route::post('/numbers-sort', 'Admin\NumberController@sortNumbers')->name('admin.numbers_sort');

    /* Slider */
    Route::get('/sliders', 'Admin\SliderController@index')->name('admin.sliders');
    Route::post('/slider-save-image', 'Admin\SliderController@saveImage')->name('admin.slider_save_image');
    Route::post('/slider-sort-images', 'Admin\SliderController@sortImages')->name('admin.slider_sort_images');
    Route::post('/slider-remove-image', 'Admin\SliderController@removeImage')->name('admin.slider_remove_image');
    Route::post('/slider-switch-active', 'Admin\SliderController@switchActive')->name('admin.slider_switch_active');

    /* Static pages */
    Route::get('/static-pages/{slug}', 'Admin\StaticPageController@edit')->name('admin.static_pages_edit');
    Route::put('/static-pages/{slug}', 'Admin\StaticPageController@update')->name('admin.static_pages_update');

    /* Gallery */
    Route::get('/gallery', 'Admin\GalleryController@index')->name('admin.gallery.show');
    Route::post('/gallery-save-image', 'Admin\GalleryController@saveImage')->name('admin.gallery_save_image');
    Route::post('/gallery-sort-images', 'Admin\GalleryController@sortImages')->name('admin.gallery_sort_images');
    Route::post('/gallery-remove-image', 'Admin\GalleryController@removeImage')->name('admin.gallery_remove_image');
    Route::post('/gallery-image-switch-active', 'Admin\GalleryController@switchActive')->name('admin.gallery_switch_active');
    Route::post('/gallery-enable-numbers-photo', 'Admin\GalleryController@enableNumbersPhoto')->name('admin.gallery_enable_numbers_photo');

    /* Info */
    Route::resource('info', 'Admin\InfoController');

    /* Text */
    Route::resource('texts', 'Admin\TextController');

    /* Feedback */
    Route::get('/feedback', 'Admin\FeedbackController@index')->name('admin.feedback.show');
});

app/Models/Number.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Carbon\CarbonPeriod;
use Illuminate\Database\Eloquent\Model;

class Number extends Model
{
    protected $fillable = [
        'title', 'description', 'sort', 'count', 'preview', 'active', 'slug'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function images()
    {
        return $this->hasMany('App\Models\NumberImage');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function cost()
    {
        return $this->hasMany('App\Models\NumberCost');
    }

    /**
     * @return Model|\Illuminate\Database\Eloquent\Relations\HasMany|object|null
     */
    public function getMainImage()
    {
        return $this->images()->where('sort', 0)->first();
    }

    /**
     * @param string $type
     * @return mixed|string|null
     */
    public function getMainImagePath(string $type = 'original')
    {
        $image = $this->images()->where('sort', 0)->first();

        $path = null;

        if($image)
        {
            switch ($type)
            {
                case 'original':
                    $path = $image->path;
                    break;

                case 'thumbnail':
                    $path = 'thumbnails/' . $image->thumbnail;
                    break;
            }
        }
        else
        {
            $path = 'default.jpeg';
        }

        return $path;
    }

    /**
     * @param null $date
     * @return mixed
     */
    public function getPrice($date = null)
    {
        $desiredDate = $date ?? Carbon::now();

        foreach ($this->cost as $cost)
        {
            $period = CarbonPeriod::create(Carbon::parse($cost->from), Carbon::parse($cost->to));

            foreach ($period as $date)
            {
                if($date->format('d.m.Y') == $desiredDate->format('d.m.Y'))
                {
                   return $cost->price;
                }
            }
        }
    }

    /**
     * @param array $dates
     * @return int
     */
    public function getSumByPeriod(array $dates)
    {
        $sum    = 0;
        $period = CarbonPeriod::create(Carbon::parse($dates[0]), Carbon::parse($dates[1]));

        foreach ($period as $date)
        {
           $sum += $this->getPrice($date);
        }

        return $sum;
    }

    /**
     * @return mixed
     */
    public static function getBySortWithActive()
    {
        return self::where('active', 1)->orderBy('sort', 'asc')->with('images')->get();
    }
}

app/Http/Controllers/Admin/NumberController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Number;
use Illuminate\Http\Request;
use App\Entities\NumberEntity;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\NumberStoreRequest;
use App\Http\Requests\Admin\NumberUpdateRequest;

class NumberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $numbers = Number::orderBy('sort','asc')->get();

        return view('admin.number.index', compact('numbers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.number.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param NumberStoreRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(NumberStoreRequest $request)
    {
        NumberEntity::adminStore($request);

        return redirect()->route('numbers.index')->with('success', 'Номер создан успешно');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $number = Number::find($id);

        return view('admin.number.edit', compact('number'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param NumberUpdateRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(NumberUpdateRequest $request, $id)
    {
        NumberEntity::adminUpdate($request, $id);

        return redirect()->back()->with('success', 'Данные успешно обновлены!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        NumberEntity::adminDestroy($id);

        return redirect()->route('numbers.index')->with('success', 'Номер был успешно УДАЛЕН!');
    }

    /**
     *  Make image with thumbnail and save them
     *
     * @param Request $request
     * @return array|string
     * @throws \Throwable
     */
    public function saveImage(Request $request)
    {
        $number = NumberEntity::adminSaveImage($request);

        return view('admin.number.list_images', compact('number'))->render();
    }

    /**
     * Sort images with drag and drop
     * @param Request $request
     * @return array|string
     * @throws \Throwable
     */
    public function sortImages(Request $request)
    {
        $number = NumberEntity::adminSortImages($request);

        return view('admin.number.list_images', compact('number'))->render();
    }

    /**
     * Switch active image
     *
     * @param Request $request
     * @return array|string
     * @throws \Throwable
     */
    public function imageSwitchActive(Request $request)
    {
        $number = NumberEntity::adminImageSwitchActive($request);

        return view('admin.number.list_images', compact('number'))->render();
    }

    /**
     * Delete image and thumbnail
     *
     * @param Request $request
     * @return array|string
     * @throws \Throwable
     */
    public function removeImage(Request $request)
    {
        $number = NumberEntity::adminRemoveImage($request);

        return view('admin.number.list_images', compact('number'))->render();
    }

    /**
     * Add price
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function addPrice(Request $request)
    {
        $numberCost = NumberEntity::adminAddPrice($request);

        return view('admin.number.new_price', compact('numberCost'));
    }

    /**
     * Remove price
     *
     * @param Request $request
     * @return string
     */
    public function removePrice(Request $request) :string
    {
        return NumberEntity::adminRemovePrice($request);
    }

    /**
     * Switch active number
     *
     * @param Request $request
     * @return array|string
     * @throws \Throwable
     */
    public function switchActive(Request $request)
    {
        $numbers = NumberEntity::adminSwitchActive($request);

        return view('admin.number.list_numbers', compact('numbers'))->render();
    }

    /**
     * Sort numbers
     *
     * @param Request $request
     */
    public function sortNumbers(Request $request)
    {
        NumberEntity::adminSortNumbers($request);
    }

}

app/Http/Controllers/Front/NumberController.php
<?php

namespace App\Http\Controllers\Front;

use App\Entities\NumberEntity;
use App\Http\Controllers\Controller;

class NumberController extends Controller
{
    /**
     * Show number
     *
     * @param $slug
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($slug)
    {
        $number = NumberEntity::frontGetBySlug($slug);

        return view('front.number.show', compact('number'));
    }
}

resources/views/admin/number/create.blade.php
@extends('layouts.admin.app')

@section('content')
    <div class="container">
        <br>
        <h3 class="text-center">
            Создать номер
        </h3>
        <br>

        <form action="{{ route('numbers.store') }}" method="POST" novalidate>
            @csrf
            @method('POST')
            <div class="form-group">
                <label for="number-title">Название</label>
                <input type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" id="number-title" name="title"  placeholder="Название" value="{{ old('title') }}" required>

                @if ($errors->has('title'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('title') }}</strong>
                    </span>
                @endif
            </div>

            <div class="form-group">
                <label for="number-preview">Превью</label>
                <input type="text" class="form-control{{ $errors->has('preview') ? ' is-invalid' : '' }}" id="number-preview" name="preview"  placeholder="Превью" value="{{ old('preview') }}" required>

                @if ($errors->has('preview'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('preview') }}</strong>
                    </span>
                @endif
            </div>

            <div class="form-group">
                <label for="number-description">Описание</label>
                <textarea class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" id="number-description" rows="3" placeholder="Описание" required>{{ old('description') }}</textarea>

                @if ($errors->has('description'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('description') }}</strong>
                    </span>
                @endif
            </div>

            <div class="pt-1 pb-2">
                <small><i>*Цены и фотографии добавляются при редактировании</i></small>
            </div>

            <div class="form-group pt-2">
                <button type="submit" class="btn btn-primary">Создать</button>
            </div>

        </form>
    </div>
@endsection

resources/views/admin/number/edit.blade.php
@extends('layouts.admin.app')

@section('content')
    <div class="container container-number" data-id="{{ $number->id }}">
        <br>
        <h3 class="text-center">Редактирование номера "{{ $number->title }}"</h3>
        <br>

        @include('admin.widgets.success_message')

        <form action="{{ route('numbers.update', ['id' => $number->id]) }}" method="POST" class="mb-5" enctype="multipart/form-data">

            @csrf
            @method('PUT')

            <!-- TITLE -->
            <div class="form-group">
                <label for="number-title">Название</label>
                <input type="text"
                       class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}"
                       id="number-title"
                       name="title"
                       placeholder="Название" value="{{ old('title') ?? $number->title }}" required>

                @if ($errors->has('title'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('title') }}</strong>
                    </span>
                @endif
            </div>

            <!-- URL -->
            <div class="form-group">
                <label for="number-url">URL</label>
                <input type="text"
                       class="form-control"
                       id="number-url"
                       name="slug"
                       value="{{ $number->slug }}" disabled>
            </div>

            <!-- PREVIEW -->
            <div class="form-group">
                <label for="number-preview">Превью</label>
                <input type="text"
                       class="form-control{{ $errors->has('preview') ? ' is-invalid' : '' }}"
                       id="number-preview"
                       name="preview"
                       placeholder="Превью"
                       value="{{ old('preview') ?? $number->preview }}" required>

                @if ($errors->has('preview'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('preview') }}</strong>
                    </span>
                @endif
            </div>

            <!-- DESCRIPTION -->
            <div class="form-group pb-3">
                <label for="number-description">Описание</label>
                <textarea class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}"
                          name="description"
                          id="number-description"
                          rows="6"
                          placeholder="Описание"
                          required>{{ old('description') ?? $number->description }}</textarea>

                @if ($errors->has('description'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('description') }}</strong>
                    </span>
                @endif
            </div>

            <hr>

            <!-- DATE -->
            <!-- Add date btn -->
            <div class="form-row pb-3">
                <button class="btn btn-outline-primary btn-sm number-add-price" type="button">
                    <i class="fas fa-plus"></i>
                    &nbsp;
                    <span>Добавить</span>
                </button>
            </div>

           <!-- labels -->
            <div class="form-row">
                <div class="form-group col-md-4 mb-0">
                    <label for="inputCity">Дата</label>
                </div>
                <div class="form-group col-md-2 mb-0">
                    <label for="inputCity">Цена</label>
                </div>
            </div>

            <!-- inputs -->
            <div class="number-prices">
                @include('admin.number.prices')
            </div>

            <hr>

            <!-- ADD IMAGE -->
            <div class="form-group mr-2 mb-0">
                <label for="number-photo-file">Добавить изображение</label>
            </div>

            <div class="form-row">
                <div class="form-group col-lg-4">
                    <input type="file" class="form-control-file" name="number-photo" id="number-photo-file">
                </div>
                <div class="form-group col-lg-6">
                    <button type="button" class="btn btn-outline-primary btn-cropper-modal" data-toggle="modal" data-target="#number-cropper-modal">
                        Открыть CROPPER
                    </button>
                </div>
            </div>

            <div class="row sortable-number-images">
                @include('admin.number.list_images')
            </div>

            <!-- SUBMIT -->
            <div class="form-group pt-2">
                <button type="submit" class="btn btn-primary">Обновить</button>
            </div>

        </form>
    </div>

    @include('admin.widgets.cropper_modal', ['id' => 'number-cropper-modal', 'btnClass' => 'crop-image-for-number'])

@endsection

resources/views/admin/number/index.blade.php
@extends('layouts.admin.app')

@section('content')
    <div class="container">
        <br>
        <h3 class="text-center">Номера</h3>
        <br>

        <a href="{{ route('numbers.create') }}" class="btn btn-outline-primary">
            <i class="fas fa-plus"></i>&nbsp;Добавить
        </a>
        <br>
        <br>

        @include('admin.widgets.success_message')

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Название</th>
                    <th scope="col">Цена</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>

            <tbody class="list-numbers-body">
                @include('admin.number.list_numbers')
            </tbody>
        </table>
    </div>
@endsection

resources/views/admin/number/list_images.blade.php
@if(!empty($number))
    @foreach($number->images->sortBy('sort') as $image)
        <div class="col-lg-3 py-3">
            <div class="card" data-id="{{ $image->id }}">

                <img class="card-img-top" src="{{ asset('storage/numbers/thumbnails/' . $image->thumbnail) }}" alt="slide">

                <div class="card-body px-2 pb-1 pt-2">
                    <div class="row">
                        <div class="col-lg-6 text-left">
                            @if($image->active)
                                <i class="fas fa-toggle-on inactive fa-2x number-image-switch-active text-success"></i>
                            @else
                                <i class="fas fa-toggle-on fa-rotate-180 inactive fa-2x number-image-switch-active text-danger"></i>
                            @endif
                        </div>
                        <div class="col-lg-6 text-right text-danger">
                            <i class="far fa-trash-alt number-image-remove"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endforeach
@endif

resources/views/admin/number/list_numbers.blade.php
@foreach($numbers as $number)
    <tr class="number-box-data" data-id="{{ $number->id }}">
        <th>{{ $number->title }}</th>
        <td>
            @if($number->getPrice())
                {{ $number->getPrice() }} грн.
            @else
                <span class="text-danger">Не заполнено</span>
            @endif
        </td>
        <td>
            @if($number->active)
                <i class="fas fa-toggle-on inactive fa-2x text-success number-switch-active"></i>
            @else
                <i class="fas fa-toggle-on fa-rotate-180 inactive fa-2x text-danger number-switch-active"></i>
            @endif
        </td>
        <td class="text-primary">
            <a href="{{ route('numbers.edit', ['id' => $number->id]) }}">
                <i class="fas fa-edit fa-lg"></i>
            </a>
        </td>
        <td class="text-danger">
            <form action="{{ route('numbers.destroy', [$number->id]) }}" method="POST" class="number-remove-form">
                @csrf
                @method('DELETE')
                <i class="far fa-trash-alt fa-lg number-remove"></i>
            </form>
        </td>
    </tr>
@endforeach

resources/views/admin/number/new_price.blade.php
@if(isset($numberCost))
    <div class="form-row number-box-price" data-id="{{ $numberCost->id }}">
        <div class="form-group col-lg-4 col-md-6 col-sm-7 col-8">
            <input type="text" class="form-control number-cost-date"
                   name="dates[{{ $numberCost->id }}]"
                   value="">
        </div>

        <div class="form-group col-lg-2 col-md-3 col-sm-4 col-3">
            <input type="text" class="form-control number-cost-price" name="prices[{{ $numberCost->id }}]" value="">
        </div>

        <div class="form-group col-lg-1 col-md-1 col-sm-1 col-1 text-danger">
            <i class="far fa-trash-alt number-price-remove align-bottom"></i>
        </div>
    </div>
@endif

<script src="{{ asset('js/custom/dp_adm_number_new_price.js') }}" defer></script>

resources/views/admin/number/prices.blade.php
@if($number->cost)
    @foreach($number->cost as $cost)
        @php
            $date = '';

            if($cost->from !==null && $cost->to !==null)
                $date = $cost->from->format('d.m.Y') . '-' . $cost->to->format('d.m.Y');

        @endphp

        <div class="form-row number-box-price" data-id="{{ $cost->id }}">

            <div class="form-group col-lg-4 col-md-6 col-sm-7 col-8">
                <input type="text" class="form-control number-cost-date {{ $errors->has('dates' . $cost->id) || $errors->has('dates') ? 'is-invalid' : '' }}"
                       name="dates[{{ $cost->id }}]"
                       value="{{ old('dates.' . $cost->id) ?? $date }}"
                       required>

                @if ($errors->has('dates.'.$cost->id))
                    <span class="invalid-feedback" role="alert" style="display: block">
                    <strong>{{ $errors->first('dates.'.$cost->id) }}</strong>
                </span>
                @endif
            </div>

            <div class="form-group col-lg-2 col-md-3 col-sm-4 col-3">
                <input type="text"
                       class="form-control number-cost-price {{ $errors->has('prices.'.$cost->id ) ? 'is-invalid' : '' }}"
                       name="prices[{{ $cost->id }}]"
                       value="{{ old('prices.' . $cost->id) ?? $cost->price }}"
                       required>

                @if ($errors->has('prices.'.$cost->id))
                    <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('prices.'.$cost->id) }}</strong>
                </span>
                @endif
            </div>

            <div class="form-group col-lg-1 col-md-1 col-sm-1 col-1 text-danger">
                <i class="far fa-trash-alt number-price-remove align-bottom"></i>
            </div>
        </div>
    @endforeach
@endif



@if($errors->has('dates'))
    <span class="invalid-feedback" role="alert" style="display: block">
        <strong>{{ $errors->first('dates') }}</strong>
    </span>
@endif